"""add_new_column

Revision ID: c3f79c33c2b4
Revises: 81b416eae473
Create Date: 2025-05-13 00:47:27.934693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3f79c33c2b4"
down_revision: Union[str, None] = "81b416eae473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "places", sa.Column("image_data", sa.LargeBinary(), nullable=True)
    )
    op.add_column(
        "places",
        sa.Column("image_mimetype", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("places", "image_mimetype")
    op.drop_column("places", "image_data")
    # ### end Alembic commands ###
